local clipboard = {}
clipboard.__index = clipboard

clipboard.settings_key = "clipboard_history"
clipboard.frequency = 0.8
clipboard.hist_size = 40
clipboard.display_max_length = 100
clipboard.persist_delay = 2
clipboard.show_in_menubar = false
clipboard.honor_ignoredidentifiers = true
clipboard.ignoredIdentifiers = {
    ["de.petermaurer.TransientPasteboardType"] = true,
    ["com.typeit4me.clipping"] = true,
    ["Pasteboard generator type"] = true,
    ["com.agilebits.onepassword"] = true,
    ["org.nspasteboard.TransientType"] = true,
    ["org.nspasteboard.ConcealedType"] = true,
    ["org.nspasteboard.AutoGeneratedType"] = true,
}

local pasteboard = require("hs.pasteboard")

local function getSetting(label, default)
    return hs.settings.get(clipboard.settings_key .. "." .. label) or default
end

local function setSetting(label, value)
    hs.settings.set(clipboard.settings_key .. "." .. label, value)
    return value
end

local function previewText(value, max_length)
    local normalized = value:gsub("[%s\r\n]+", " ")
    local utf8_length = utf8.len(normalized)

    if not utf8_length then
        if #normalized <= max_length then
            return normalized
        end
        return normalized:sub(1, max_length - 1) .. "..."
    end

    if utf8_length <= max_length then
        return normalized
    end

    local cutoff = utf8.offset(normalized, max_length + 1)
    if cutoff == nil then
        return normalized
    end

    return normalized:sub(1, cutoff - 1) .. "..."
end

local function charCount(value)
    return utf8.len(value) or #value
end

function clipboard:_persistHistory()
    setSetting("items", self.history)
end

function clipboard:_schedulePersist()
    if self.persist_timer ~= nil then
        self.persist_timer:stop()
    end

    self.persist_timer = hs.timer.doAfter(self.persist_delay, function()
        self.persist_timer = nil
        self:_persistHistory()
    end)
end

function clipboard:_shouldStore()
    if not self.honor_ignoredidentifiers then
        return true
    end

    for _, identifier in ipairs(pasteboard.pasteboardTypes() or {}) do
        if self.ignoredIdentifiers[identifier] then
            return false
        end
    end

    for _, identifier in ipairs(pasteboard.contentTypes() or {}) do
        if self.ignoredIdentifiers[identifier] then
            return false
        end
    end

    return true
end

function clipboard:_addItem(item)
    if item == nil or item == "" then
        return
    end

    if self.history[1] == item then
        return
    end

    for i, existing in ipairs(self.history) do
        if existing == item then
            table.remove(self.history, i)
            break
        end
    end

    table.insert(self.history, 1, item)

    while #self.history > self.hist_size do
        table.remove(self.history)
    end

    self:_schedulePersist()
end

function clipboard:_processChoice(choice)
    if self.prev_focused_window ~= nil then
        self.prev_focused_window:focus()
    end

    if choice == nil then
        return
    end

    if choice.action == "clear" then
        pasteboard.clearContents()
        self.history = {}
        self:_persistHistory()
        self.last_change = pasteboard.changeCount()
        return
    end

    if choice.clipboard ~= nil then
        pasteboard.setContents(choice.clipboard)
        self:_addItem(choice.clipboard)
        self.last_change = pasteboard.changeCount()
    end
end

function clipboard:_buildChoices()
    local choices = {}

    for _, value in ipairs(self.history) do
        table.insert(choices, {
            text = previewText(value, self.display_max_length),
            subText = string.format("%s chars", charCount(value)),
            clipboard = value,
        })
    end

    if #choices == 0 then
        table.insert(choices, {
            text = "",
            subText = "Clipboard is empty",
            action = "empty",
            image = hs.image.imageFromName("NSCaution"),
        })
    else
        table.insert(choices, {
            text = "Clear Clipboard History",
            action = "clear",
            image = hs.image.imageFromName("NSTrashFull"),
        })
    end

    return choices
end

function clipboard:_checkAndStore()
    local now = pasteboard.changeCount()
    if now <= self.last_change then
        return
    end

    if self:_shouldStore() then
        local contents = pasteboard.getContents()
        if contents ~= nil then
            self:_addItem(contents)
        end
    end

    self.last_change = now
end

function clipboard:show()
    self.prev_focused_window = hs.window.focusedWindow()
    self.chooser:refreshChoicesCallback()
    self.chooser:show()
end

function clipboard:toggle()
    if self.chooser:isVisible() then
        self.chooser:hide()
        return
    end

    self:show()
end

function clipboard:start()
    if self.timer ~= nil then
        return self
    end

    self.history = getSetting("items", {})
    while #self.history > self.hist_size do
        table.remove(self.history)
    end
    self.last_change = pasteboard.changeCount()
    self.chooser = hs.chooser.new(function(choice)
        self:_processChoice(choice)
    end)
    self.chooser:rows(12)
    self.chooser:searchSubText(false)
    self.chooser:choices(function()
        return self:_buildChoices()
    end)

    self.timer = hs.timer.new(self.frequency, function()
        self:_checkAndStore()
    end)
    self.timer:start()

    if self.show_in_menubar then
        self.menubar = hs.menubar.new()
        self.menubar:setTitle("CL")
        self.menubar:setClickCallback(function()
            self:toggle()
        end)
    end

    return self
end

function clipboard:stop()
    if self.timer ~= nil then
        self.timer:stop()
        self.timer = nil
    end

    if self.persist_timer ~= nil then
        self.persist_timer:stop()
        self.persist_timer = nil
    end

    if self.menubar ~= nil then
        self.menubar:delete()
        self.menubar = nil
    end

    self:_persistHistory()
end

function clipboard:init(config)
    if config ~= nil then
        for key, value in pairs(config) do
            self[key] = value
        end
    end

    self:start()

    if self.hotkey ~= nil then
        hs.hotkey.bind(self.hotkey[1], self.hotkey[2], function()
            self:toggle()
        end)
    end

    return self
end

return clipboard
