[shell]
lang = "zh-Hans"
telemetry_enabled = false
setup_wizard_enabled = true
polkit_agent = true
clipboard_enabled = true
app_icon_colorize = false
app_icon_color = "on_surface"

[notification]
enable_daemon = true
position = "top_right"

[brightness]
enable_ddcutil = true

[brightness.monitor.eDP-1]
backend = "backlight"

[brightness.monitor.DP-3]
backend = "ddcutil"

[lockscreen]
enabled = true
fingerprint = true
allow_empty_password = false
blurred_desktop = false
blur_intensity = 0.25
tint_intensity = 0.30

[idle]
pre_action_fade_seconds = 2.0

[idle.behavior.lock]
enabled = true
timeout = 600
command = "noctalia:screen-lock"

[idle.behavior.screen-off]
enabled = true
timeout = 660
command = "wlopm --off '*'"
resume_command = "wlopm --on '*'"

[shell.greeter_sync]
auto_sync = true

[shell.panel]
open_near_click_control_center = true

[theme.templates]
enable_builtin_templates = false
builtin_ids = []

[theme.templates.user.labwc]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/labwc.conf"
output_path = "$XDG_CONFIG_HOME/labwc/noctalia.conf"
post_hook = "bash /usr/share/noctalia/assets/templates/labwc/apply.sh && labwc --reconfigure"

[bar.main]
thickness = 34
scale = 1.12
start = [
    "control-center",
    "launcher",
    "wallpaper",
    "workspaces",
    "network-speed"
]
center = [
    "center-clock"
]
end = [
    "tray",
    "notifications",
    "clipboard",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "session"
]

[widget.network-speed]
type = "lucius/network-speed:network-speed"

[widget.center-clock]
type = "lucius/center-clock:center-clock"

[plugins]
enabled = ["lucius/network-speed", "lucius/center-clock"]
