[shell]
lang = "zh-Hans"
font_family = "PragmataPro"
telemetry_enabled = false
setup_wizard_enabled = true
polkit_agent = true
clipboard_enabled = true
app_icon_colorize = true
app_icon_color = "on_surface"

[notification]
enable_daemon = true
position = "top_right"

[brightness]
enable_ddcutil = true

[brightness.monitor.eDP-1]
backend = "backlight"

[brightness.monitor.DP-3]
backend = "ddcutil"

[lockscreen]
enabled = true
fingerprint = true
allow_empty_password = false
blurred_desktop = false
blur_intensity = 0.25
tint_intensity = 0.30

[idle]
pre_action_fade_seconds = 2.0

[system.monitor]
network_poll_seconds = 1.0

[idle.behavior.lock]
enabled = true
timeout = 600
command = "noctalia:screen-lock"

[idle.behavior.screen-off]
enabled = true
timeout = 660
command = "wlopm --off '*'"
resume_command = "wlopm --on '*'"

[shell.greeter_sync]
auto_sync = true

[shell.panel]
open_near_click_control_center = true

[theme.templates]
enable_builtin_templates = false
builtin_ids = []

[theme.templates.user.labwc]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/labwc.conf"
output_path = "$XDG_CONFIG_HOME/labwc/noctalia.conf"
post_hook = "bash /usr/share/noctalia/assets/templates/labwc/apply.sh && labwc --reconfigure"

[bar.main]
thickness = 34
scale = 1.12
start = [
    "control-center",
    "launcher",
    "wallpaper",
    "workspaces",
    "group:network-info"
]
center = [
    "center-clock"
]
end = [
    "tray",
    "notifications",
    "clipboard",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "session"
]

[[bar.main.capsule_group]]
id = "network-info"
members = ["network", "network-download", "network-upload"]
fill = "surface_variant"
padding = 6.0
enabled = true

[widget.network]
show_label = false

[widget.network-download]
type = "sysmon"
stat = "net_rx"
glyph = "arrow-down"
display = "text"
network_speed_compact = true

[widget.network-upload]
type = "sysmon"
stat = "net_tx"
glyph = "arrow-up"
display = "text"
network_speed_compact = true

[widget.center-clock]
type = "lucius/center-clock:center-clock"

[plugins]
enabled = ["lucius/center-clock"]
