# 设置配置范例，开启编辑器的自动补全
"$schema" = 'https://starship.rs/config-schema.json'

# 在命令之间插入空行
add_newline = false
# ~/.config/starship.toml

# A minimal left prompt
format = """$character"""
# move the rest of the prompt to the right
right_format = """$all"""
[line_break]
disabled = true
# 将提示符的“❯”替换为“➜”
[character] # “character”是我们正在配置的组件
success_symbol = "[❯](bold green)" # 设置“success_symbol” 字段为绿色加粗的“➜”

# 禁用 package 组件，完全隐藏它的提示符
[package]
disabled = true

[localip]
ssh_only = true
format = "@[$localipv4](bold red) "
disabled = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:none"
format = '[[♥ $time ](bg:none)]($style)'
